# Generated by Django 4.1.2 on 2022-11-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de sitio')),
                ('Red', models.CharField(max_length=50, verbose_name='Nombre de red')),
                ('Enlace', models.CharField(max_length=10, verbose_name='Numero de enlace')),
                ('punta', models.CharField(max_length=10, verbose_name='Punta (A/B)')),
                ('dir_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.direccion')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
            },
        ),
    ]
