# Generated by Django 4.1.3 on 2022-11-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0003_alter_direccion_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidoP', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellidoM', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('FecNac', models.DateField(blank=True, null=True)),
                ('Usuario_activo', models.BooleanField(default=True, verbose_name='Está activo')),
                ('Usuario_administrator', models.BooleanField(default=False, verbose_name='Administrador')),
                ('Usuario_engineer', models.BooleanField(default=False, verbose_name='Ingeniero')),
                ('dir_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.direccion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
