# Generated by Django 4.1.2 on 2022-11-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='FecNac',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dir_id',
            field=models.IntegerField(null=True),
        ),
    ]
