# Generated by Django 4.1.2 on 2022-11-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_fecnac_alter_usuario_dir_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dir_id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FecNac',
            field=models.DateField(blank=True),
        ),
    ]
