# Generated by Django 4.1.2 on 2022-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_usuario_fecnac'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='FecNac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
