# Generated by Django 4.1.2 on 2022-11-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuario_fecnac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='FecNac',
        ),
    ]
