# Generated by Django 4.1.2 on 2022-11-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_remove_usuario_fecnac'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='FecNac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dir_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
