# Generated by Django 4.1.2 on 2022-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('Estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('Municipio', models.CharField(max_length=30, verbose_name='Municipio')),
                ('Ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('Colonia', models.CharField(max_length=50, verbose_name='Colonia')),
                ('Calle', models.CharField(max_length=30, verbose_name='Calle')),
                ('Numero', models.CharField(max_length=10, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
